default:
  tags:
    - docker
  # Image from https://hub.docker.com/_/gcc/ based on Debian
  image: gcc

.autotools:
  stage: build
  before_script:
    - apt-get update &&
      apt-get install -y libogg-dev libvorbis-dev
        libao-dev libflac-dev libspeex-dev libkate-dev liboggkate-dev
        gettext zip ${INSTALL_COMPILER} ${INSTALL_EXTRA}
  script:
    - ./autogen.sh
    - ./configure ${CONFIG_FLAGS} || cat config.log
    - make
    - make check
  variables:
    INSTALL_COMPILER: gcc

autotools-gcc:
  extends: .autotools
  script:
    - ./autogen.sh
    - ./configure ${CONFIG_FLAGS} || cat config.log
    - make
    - make distcheck
  artifacts:
    paths:
     - vorbis-tools-*.tar.gz
     - vorbis-tools-*.zip
    expire_in: 2 week

autotools-gcc-builddir:
  extends: .autotools
  script:
    - ./autogen.sh
    - mkdir build
    - (cd build && ../configure ${CONFIG_FLAGS}) || cat config.log
    - (cd build && make)
    - (cd build && make check)

autotools-clang:
  extends: .autotools
  script:
    - ./autogen.sh
    - ./configure ${CONFIG_FLAGS} || cat config.log
    - make
    - make distcheck
  variables:
    INSTALL_COMPILER: clang
    CC: clang

autotools-enable-gcc-sanitizers:
  extends: .autotools
  variables:
    INSTALL_EXTRA: libtool
    CONFIG_FLAGS: --enable-gcc-sanitizers
